sudo: false
language: node_js
node_js:
  - "5.5.0"
install:
  - npm cache clean
  - npm prune
  - npm install
  - npm uninstall gulp
  - npm install "gulpjs/gulp.git#4.0" --save-dev
  - npm install -g typescript@2.1.4
script:
  - git status
  - gulp --version
  - npm run gulp -v
  - npm run gulp release
after_failure:
  - cat /home/travis/build/pivotal-sg/torus/npm-debug.log