sudo: false
language: node_js
node_js:
  - "5.5.0"
install:
  - npm cache clean
  - npm prune
  - ls node_modules
  - npm install
  - npm install -g typescript@2.1.4
  - ls node_modules
script:
  - npm run gulp release
after_failure:
  - cat /home/travis/build/pivotal-sg/torus/npm-debug.log